# serverless.yml
service: gltf-converter

custom:
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  environment:
    S3_REGION: ${self:custom.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::${self:service}-${opt:stage}"
        - "arn:aws:s3:::${self:service}-${opt:stage}/*"

functions:
  converter:
    handler: handler.converter
    name: ${opt:stage}-gltb-converter
    description: glTF converter as a service
    events:
      - s3:
          bucket: ${self:service}-${opt:stage}
          event: s3:ObjectCreated:*
